# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Wonderful
subtitle: '阿甘'
description: ''
keywords:
author: yasheng
#language: en
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wuyasheng.github.io/
root: /

#permalink: :year/:month/:day/:title/
# permalink: posts/:title/
# permalink_defaults:
#  pretty_urls:
#    trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
#    trailing_html: true # Set to false to remove trailing '.html' from permalinks

#将文件路径编码成数字，取消上文中的年月日等多级目录
permalink: posts/:abbrlink/
abbrlink:
  alg: crc32 #support crc16(default) and crc32
  rep: dec   #support dec(default) and hex


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false


post_asset_folder: false


relative_link: false
future: true 
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:





# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 15
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 18
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

#theme: landscape
#theme: hexo-theme-materialized-master

theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html

deploy:
  type: git
  repository: git@github.com:wuyasheng/wuyasheng.github.io.git
  branch: master



#搜索功能
search:
  path: search.xml
  field: post

#拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'


live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-shizuku
  display:
    position: right
    width: 160
    height: 320
  mobile:
    show: false
  react:
    opacity: 0.5


#懒加载,当滚轮划到图片时才进行加载

lazyload:
  enable: true
  onlypost: true
  loadingImg: /medias/loading/loading.gif


# 博客源文件备份配置
backup:
    type: git
    repository:
       github: git@github.com:wuyasheng/wuyasheng.github.io.git,hexo


aplayer:
  meting: true







